# Pulling from the httpd image and pulling the specific tag of 2.4
FROM httpd:2.4

# Copying a file on my local machine into the file system of the docker container
COPY index.html /usr/local/apache2/htdocs/
